name: example

dependencies:
  hive_ce: any

dev_dependencies:
  rexios_lints: ^7.0.0
  hive_ce_generator: any
  build_runner: any

environment:
  sdk: ^3.0.0

dependency_overrides:
  hive_ce:
    path: ../
  hive_ce_generator:
    path: ../../hive_generator