name: example

dependencies:
  hive_ce: any
  freezed_annotation: ^2.4.4

dev_dependencies:
  rexios_lints: ^7.0.0
  hive_ce_generator: any
  build_runner: ^2.4.12
  freezed: ^2.5.7

environment:
  sdk: ^3.0.0

dependency_overrides:
  hive_ce:
    path: ../
  hive_ce_generator:
    path: ../../hive_generator
