name: example

dependencies:
  hive_ce: any
  freezed_annotation: ^2.4.4

dev_dependencies:
  rexios_lints: ^8.2.0
  hive_ce_generator: any
  build_runner: any
  freezed: ^2.5.7

environment:
  sdk: ^3.0.0

dependency_overrides:
  hive_ce:
    path: ../
  hive_ce_generator:
    # TODO: Revert
    # path: ../../hive_generator
    git:
      url: https://github.com/IO-Design-Team/hive_ce
      ref: 4f06756e5eee0b027f2e9d623e8136620309afcb
      path: hive_generator
