name: example

dependencies:
  hive: any

dev_dependencies:
  hive_generator: any
  build_runner: any

environment:
  sdk: ^3.0.0

dependency_overrides:
  hive:
    path: ../
  hive_generator:
    path: ../../hive_generator