builders:
  hive_type_adapter_generator:
    import: "package:hive_ce_generator/hive_generator.dart"
    builder_factories: ["getTypeAdapterBuilder"]
    build_extensions: { ".dart": ["hive_generator.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
  hive_registrar_intermediate_generator:
    import: "package:hive_ce_generator/hive_generator.dart"
    builder_factories: ["getRegistrarIntermediateBuilder"]
    build_extensions: { ".dart": [".hive_registrar.info"] }
    auto_apply: dependents
    build_to: cache
    runs_before: ["hive_registrar_generator"]
  hive_registrar_generator:
    import: "package:hive_ce_generator/hive_generator.dart"
    builder_factories: ["getRegistrarBuilder"]
    build_extensions: { "$lib$": ["hive_registrar.g.dart"] }
    auto_apply: dependents
    build_to: source
