name: Dart CI

on: [push, pull_request]

jobs:
  test-hive:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-platform: [vm, chrome]
        dart-channel: ["3.4.0"]
        include:
          - test-platform: vm
            compiler: kernel
          - test-platform: chrome
            compiler: dart2js
          - test-platform: chrome
            compiler: dart2wasm
    steps:
      - uses: actions/checkout@v4
      - uses: browser-actions/setup-chrome@v1
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.dart-channel }}
      - name: Install dependencies
        run: dart pub get
        working-directory: hive
      - name: Run tests
        run: dart test -p ${{ matrix.test-platform }} -c ${{ matrix.compiler }}
        working-directory: hive

  test-hive-flutter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutter-channel: [beta, stable]
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.flutter-channel }}
      - name: Override dependency version
        run: |
          echo -e "\ndependency_overrides:\n  win32: 2.6.1" >> pubspec.yaml
        working-directory: hive_flutter
      - name: Install dependencies
        run: flutter pub get
        working-directory: hive_flutter
      - name: Run tests
        run: flutter test
        working-directory: hive_flutter

  test-hive_generator:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dart-channel: ["3.4.0"]
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.dart-channel }}
      - name: Install dependencies
        run: dart pub get
        working-directory: hive_generator/example
      - name: Generate build_runner output
        run: dart pub run build_runner build --delete-conflicting-outputs
        working-directory: hive_generator/example

  check-score:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [hive, hive_generator, hive_flutter]
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: |
          cd ${{ matrix.package }}
          flutter pub get
          dart pub global activate pana
          pana --no-warning --exit-code-threshold 0
